name: Build Flet APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # اضافه کردن جاوا (برای کامپایل اندروید و Gradle حیاتی است)
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build APK with Flet
        run: flet build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gold-mobile-apk
          path: build/apk/app-release.apk
